---
apiVersion: v1
kind: Service
metadata:
  name: jo25672-test-redis-service
  labels:
    username: jo25672
    env: test
spec:
  type: ClusterIP
  selector:
    app: jo25672-test-redis
  ports:
  - name: jo25672-test-redis
    port: 6379
    targetPort: 6379