---
apiVersion: v1
kind: Service
metadata:
  name: jo25672-test-geneapi-service
  labels:
    username: jo25672
    env: test
spec:
  type: ClusterIP
  selector:
    app: jo25672-test-geneapi
  ports:
  - name: jo25672-test-geneapi
    port: 5000
    targetPort: 5000