---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jo25672-test-geneapi
  labels:
    app: jo25672-test-geneapi
    username: jo25672
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jo25672-test-geneapi
  template:
    metadata:
      labels:
        app: jo25672-test-geneapi
        username: jo25672
        env: test
    spec:
      containers:
        - name: jo25672-test-geneapi
          image: jo25672/gene_api:k8
	  ports:
	  - containerPort: 5000