---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jo25672-test-redis-pvc
  labels:
    username: jo25672
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi